### ISSUE TITLE
Bug in preassembly code

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#1057]
I'm trying to get the rational enrichment workflow back up and running (hence the non PyPI install below) and I'm getting an error from the INDRA side. To reproduce, run the following code:

```bash
$ pip install git+https://github.com/bel-enrichment/bel-enrichment.git
$ bel-enrichment from-pmids 20585587
```

It looks like some of the old preassembly code didn't get refactored with the new database API.
 
```python-traceback
Traceback (most recent call last):
  File "/Users/cthoyt/.virtualenvs/enveda/bin/bel-enrichment", line 11, in <module>
    load_entry_point('bel-enrichment', 'console_scripts', 'bel-enrichment')()
  File "/Users/cthoyt/.virtualenvs/enveda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cthoyt/.virtualenvs/enveda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cthoyt/.virtualenvs/enveda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cthoyt/.virtualenvs/enveda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cthoyt/.virtualenvs/enveda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cthoyt/dev/bel-enrichment/src/bel_enrichment/cli.py", line 100, in from_pmids
    minimum_belief=belief_cutoff,
  File "/Users/cthoyt/dev/bel-enrichment/src/bel_enrichment/indra_utils.py", line 115, in get_and_write_statements_from_pmids
    minimum_belief=minimum_belief,
  File "/Users/cthoyt/dev/bel-enrichment/src/bel_enrichment/indra_utils.py", line 137, in print_statements
    statements = run_preassembly(statements)
  File "/Users/cthoyt/.virtualenvs/enveda/lib/python3.7/site-packages/indra/tools/assemble_corpus.py", line 424, in run_preassembly
    run_preassembly_duplicate(pa, be, save=dump_pkl_unique)
  File "/Users/cthoyt/.virtualenvs/enveda/lib/python3.7/site-packages/indra/tools/assemble_corpus.py", line 458, in run_preassembly_duplicate
    len(preassembler.stmts))
TypeError: object of type 'IndraDBRestPaperProcessor' has no len()
```

**Comment by bgyori** [comment]
I believe this is due to a change in the `indra_db_rest` API which now, by default returns a Processor object rather than a flat list of Statements. If you use the Processor's `statements` attribute, you will get a list of Statements that you can work with for assembly, etc.

**Comment by cthoyt** [comment]
Ahh i see. The type annotations for `indra_db_rest.get_statements_for_paper` didn't get picked up for pycharm because there's now an option `simple_response=True` to revert it to old behavior. Thanks!

**Comment by bgyori** [comment]
Yes, `simple_response=True` is an option but the Processor typically carries useful additional metadata so it's worth using that for most use cases.
