### ISSUE TITLE
Unable to run path between protein entities

### ISSUE THREAD

**Issue by olhakholod** [sorgerlab/indra#1066]
Hello!

I would like to run the following query:

```
from indra.sources import biopax
# Process the neighborhood of BRAF and MAP2K1
biopax_processor = biopax.process_pc_pathsfromto(['BRAF', 'RAF1'], ['MAP2K1', 'MAP2K2'])

```
I have installed jnius library and edited info.plist file in Java library. However, I got an error message:

```
Traceback (most recent call last):
  File "indra_test.py", line 3, in <module>
    biopax_processor = biopax.process_pc_pathsfromto(['BRAF', 'RAF1'], ['MAP2K1', 'MAP2K2'])
  File "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/sources/biopax/api.py", line 145, in process_pc_pathsfromto
    return process_model(model)
  File "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/sources/biopax/api.py", line 198, in process_model
    bp.get_modifications()
  File "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/sources/biopax/processor.py", line 118, in get_modifications
    stmts = self._get_generic_modification(modclass)
  File "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/sources/biopax/processor.py", line 674, in _get_generic_modification
    enzs = BiopaxProcessor._get_primary_controller(controller_pe)
  File "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/sources/biopax/processor.py", line 730, in _get_primary_controller
    members = BiopaxProcessor._get_complex_members(controller_pe)
  File "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/sources/biopax/processor.py", line 596, in _get_complex_members
    s in cplx.getComponentStoichiometry().toArray()}
  File "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/sources/biopax/processor.py", line 596, in <dictcomp>
    s in cplx.getComponentStoichiometry().toArray()}
AttributeError: 'org.biopax.paxtools.model.level3.PhysicalEntity' object has no attribute 'getUri'

```
What should I do to fix this error?

Thank you!

**Comment by bgyori** [comment]
Hi @olhakholod, I just tried this example and it worked for me with the latest master of INDRA (though this part of INDRA has not changed for quite a while so if you have a slightly older version, that should work too). My suspicion is that you have a version of Java that is not compatible with the version of paxtools that comes packaged with INDRA. We have looked into supporting various newer Java versions but the one that we know is stable and tested with INDRA's dependencies is 1.8. For instance, on my Mac, I have
```
$ java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
So I suggest that you try to install Java 1.8 and see if that fixes this issue.

**Comment by olhakholod** [comment]
My java version is 1.8. 

```
Olhas-MacBook-Pro:~ olha$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

I have tried older versions of java (like 1.7) and still get the same error.

**Comment by bgyori** [comment]
I couldn't reproduce the issue and am not totally sure what might cause this. Here is one idea to try in a python shell:
```
In [1]: from indra.sources import biopax                                                            
In [2]: import os                                                                                   
In [3]: os.environ['CLASSPATH']                                                                     
Out[3]: '<path_to_indra>/indra/sources/biopax/jars/paxtools.jar:...'
In [4]: os.environ['JAVA_HOME']                                                                     
Out[4]: '/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/'
```
In the first output you should see paxtools.jar in the INDRA repository which in your case should be under "/Users/olha/miniconda3/lib/python3.6/site-packages/indra/". In the second output, you should make sure that you see jdk1.8.*.

**Comment by bgyori** [comment]
With #1133, the BioPAX processor doesn't use jnius anymore so this shouldn't be a problem.
