### ISSUE TITLE
Error on BioPAX Parsing of Reactome content

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#1184]
It appears that there are some issues with none-types when processing content from Reactome. It can be reproduced with (pybiopax==0.0.4, indra==1.18.0):

```python
import pybiopax
import indra.sources.biopax
biopax_model = pybiopax.model_from_owl_url('https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level3/1643685')
bp = indra.sources.biopax.process_model(model)
INFO: [2020-10-27 18:01:19] indra.ontology.bio.ontology - Loading INDRA bio ontology from cache at /Users/cthoyt/.indra/bio_ontology/1.2/bio_ontology.pkl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/api.py", line 208, in process_model
    bp.process_all()
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 59, in process_all
    self.get_modifications()
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 258, in get_modifications
    for enz, sub, gained_mods, lost_mods, \
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 239, in _conversion_state_iter
    for inp, outp in self.find_matching_left_right(conversion):
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 149, in find_matching_left_right
    return BiopaxProcessor.find_matching_entities(left_simple, right_simple)
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 183, in find_matching_entities
    matches += BiopaxProcessor.find_matching_entities(inp_members,
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 183, in find_matching_entities
    matches += BiopaxProcessor.find_matching_entities(inp_members,
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 161, in find_matching_entities
    input_ers = {mpe.entity_reference.uid
  File "/Users/cthoyt/dev/bel/indra/indra/sources/biopax/processor.py", line 161, in <setcomp>
    input_ers = {mpe.entity_reference.uid
AttributeError: 'NoneType' object has no attribute 'uid'
```

**Comment by bgyori** [comment]
Thanks! Looking at the error, this is probably an instance where Reactome's own BioPAX export doesn't follow the same conventions as PathwayCommons. Since we ingest Reactome via PathwayCommons, the export that is tested and quality-controlled to work well with INDRA is https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.BIOPAX.owl.gz. I'll look into how Reactome's own export differs from this and will comment here.

**Comment by bgyori** [comment]
I pushed a branch called `biopax_fix` that fixes this error, but just by looking at the statements that are extracted, some of them look a little bit strange, e.g., 
```
Phosphorylation(FGFR2b C382R mutant dimer(), FGFR2(), Y),
Phosphorylation(FGFR2 L764fs*4STOP mutant dimer(), FGFR2(), Y),
Phosphorylation(FGFR2(22-767)-CASP7(1-303) fusion dimer(), FGFR2(), Y, 466),
Phosphorylation(ERBB2 KD mutants:Ligand-Activated EGFR,ERBB3,(ERBB4)(), ERBB3(), Y, 1289),
```
The ones with these long names come out as ungrounded agents and it would probably require more work to track down how the underlying BioPAX is different from PathwayCommons to improve on this.

**Comment by Rajeswara-Rao** [comment]
Hello @bgyori , 
1.I tried to convert OWL file(Downloaded from https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.BIOPAX.owl.gz. ) into BEL script, But I am facing _TypeError: object of type 'int' has no len()_. Please help me to resolve this error.

2.Would you please provide me the solution that how do you use `biopax_fix` to fix _AttributeError: 'NoneType' object has no attribute 'uid'_

```
import indra.sources.biopax
import pybel
import pybiopax

apoptosis_path = r'C:\Users\vlakkara\Desktop\PathwayCommons12.reactome.BIOPAX.owl'

with open(apoptosis_path, 'r', encoding='utf-8') as file:
    owl_str = file.read()
    biopax_model = pybiopax.model_from_owl_str(owl_str)

biopax_processor = indra.sources.biopax.process_model(biopax_model)
---------------------------------------------------------------------------
Processing OWL elements: 100%|███████████████████████████████████████████████| 438368/438368 [03:49<00:00, 1906.29it/s]
```
```
graph = pybel.from_indra_statements(biopax_processor.statements)
pybel.to_bel_script(graph,r'C:\Users\vlakkara\Desktop\example.belns')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-42da1b30f564> in <module>
----> 1 pybel.to_bel_script(graph,r'C:\Users\vlakkara\Desktop\example.belns')

<decorator-gen-874> in to_bel_script(graph, path)

~\Anaconda3\lib\site-packages\networkx\utils\decorators.py in _open_file(func_to_be_decorated, *args, **kwargs)
    237         # Finally, we call the original function, making sure to close the fobj
    238         try:
--> 239             result = func_to_be_decorated(*new_args, **kwargs)
    240         finally:
    241             if close_fobj:

~\Anaconda3\lib\site-packages\pybel\canonicalize.py in to_bel_script(graph, path)
     41 def to_bel_script(graph, path: Union[str, TextIO], use_identifiers: bool = True) -> None:
     42     """Write the BELGraph as a canonical BEL script.
---> 43 
     44     :param BELGraph graph: the BEL Graph to output as a BEL Script
     45     :param path: A path or file-like.

~\Anaconda3\lib\site-packages\pybel\canonicalize.py in _to_bel_lines_body(graph)
    263         annotation_patterns=graph.annotation_pattern,
    264         annotation_list=graph.annotation_list,
--> 265         **graph.document,
    266     )
    267 

~\Anaconda3\lib\site-packages\pybel\canonicalize.py in _set_annotation_to_str(annotation_data, key)
    201     return (
    202         t[3][CITATION][CITATION_DB],
--> 203         t[3][CITATION][CITATION_IDENTIFIER],
    204         t[3][EVIDENCE],
    205     )

TypeError: object of type 'int' has no len()
```

**Comment by cthoyt** [comment]
This looks like a problem with INDRA generating BEL that uses integers instead of strings as citation identifiers... PyBEL should probably be a bit more defensive with that, but it's in a big change right now so I can make a PR to INDRA that fixes this too

**Comment by cthoyt** [comment]
@bgyori I'd guess PathwayCommons does some processing in the middle to clean up what's in Reactome. However, I think it would be okay to merge https://github.com/bgyori/indra/tree/biopax_fix before addressing that.

Unfortunately, as long as the functions are called "from_biopax" or something like that, I think users will continue to misunderstand to what kind of BioPAX datasource it is really useful (even if the docs say so!)

**Comment by bgyori** [comment]
@cthoyt and @Rajeswara-Rao, I wasn't able to replicate the PMID int issue from `PathwayCommons12.reactome.BIOPAX.owl`, though I didn't do this through PyBEL, just used INDRA as:
```
from indra.sources import biopax
from indra.statements.validate import *
bp = biopax.process_owl('PathwayCommons12.reactome.BIOPAX.owl')
print_validation_report(bp.statements)  # -> doesn't print anything
# Just in case, I did an additional check which didn't print anything either
for stmt in bp.statements:
    for ev in stmt.evidence:
        if isinstance(ev.pmid, int):
            print('INT PMID')
```
I might be missing something on my end, but do you think the ints could somehow be introduced at another stage of conversion outside INDRA?

**Comment by bgyori** [comment]
I tried the code above that goes through PyBEL and got a somewhat different error, probably because I am using a different version of PyBEL (I have 0.14.10):

```
~/.virtualenvs/py37/lib/python3.7/site-packages/pybel/canonicalize.py in _set_annotation_to_str(annotation_data, key)
    233     value = annotation_data[key]
    234 
--> 235     if len(value) == 1:
    236         return 'SET {} = "{}"'.format(key, list(value)[0])
    237 

TypeError: object of type 'int' has no len()

ipdb> value                                                                                             
1
ipdb> annotation_data                                                                                   
{'stmt_hash': 22012861728236026, 'uuid': 'd2b1f650-024b-4872-81ce-a74a8bd43580', 'belief': 1, 'source_hash': -3024769831328984929, 'source_api': 'biopax', 'source_id': 'http://www.reactome.org/biopax/74/1643685#Catalysis1'}
ipdb> l                                                                                                 
    230 
    231 def _set_annotation_to_str(annotation_data: Mapping[str, Mapping[str, bool]], key: str) -> str:
    232     """Return a set annotation string."""
    233     value = annotation_data[key]
    234 
--> 235     if len(value) == 1:
    236         return 'SET {} = "{}"'.format(key, list(value)[0])
    237 
    238     x = ('"{}"'.format(v) for v in sorted(value))
    239 
    240     return 'SET {} = {{{}}}'.format(key, ', '.join(x))
```
As you see, what happens in my case is related to the `belief` annotation being an int (actually, it's more generally a float but that's beside the point).

**Comment by cthoyt** [comment]
Oh... I know what the issue is. Since we wrote all of the INDRA -> PyBEL code before there were lots of helper `add_edge`-like functions, we sort of just used the native `networkx.Graph.add_edge()`. This means that some of the INDRA-specific data gets added in a schema that can't be written to BEL script with the existing code. I can provide a PR for this

**Comment by bgyori** [comment]
I think this is definitely solved now, let me know if issues come up again.
