### ISSUE TITLE
Documentation error related to new PyBEL version

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#1212]
```python
WARNING: autodoc: failed to import module 'bel.processor' from module 'indra.sources'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/sources/bel/__init__.py", line 1, in <module>
    from .api import process_large_corpus, process_small_corpus, \
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/sources/bel/api.py", line 11, in <module>
    from .processor import PybelProcessor
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/sources/bel/processor.py", line 23, in <module>
    from indra.assemblers.pybel.assembler import _pybel_indra_act_map
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/assemblers/pybel/__init__.py", line 1, in <module>
    from .assembler import PybelAssembler
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/assemblers/pybel/assembler.py", line 31, in <module>
    'gap': activity_mapping['gap'],
NameError: name 'Entity' is not defined
```

**Comment by bgyori** [comment]
This seems to be related to the fact that several PyBEL modules are mocked out in the documentation configuration and so `Entity` is never imported.
