### ISSUE TITLE
BioPAX API paths-from-to query fails

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#182]
Looks like something to do with string encoding.
```
======================================================================
ERROR: test_biopax.test_pathsfromto
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/bgyori/indra/indra/tests/test_biopax.py", line 158, in test_pathsfromto
    bp = biopax.process_pc_pathsfromto(['MAP2K1'], ['MAPK1'])
  File "/home/travis/build/bgyori/indra/indra/biopax/biopax_api.py", line 115, in process_pc_pathsfromto
    target_genes, neighbor_limit)
  File "/home/travis/build/bgyori/indra/indra/biopax/pathway_commons_client.py", line 80, in graph_query
    model = owl_str_to_model(res.content)
  File "/home/travis/build/bgyori/indra/indra/biopax/pathway_commons_client.py", line 103, in owl_str_to_model
    istream = bais(jstr(owl_str).getBytes(scs.UTF_8));
  File "jnius/jnius_export_class.pxi", line 157, in jnius.JavaClass.__init__ (jnius/jnius.c:18763)
  File "jnius/jnius_export_class.pxi", line 234, in jnius.JavaClass.call_constructor (jnius/jnius.c:20026)
  File "jnius/jnius_conversion.pxi", line 22, in jnius.release_args (jnius/jnius.c:7604)
  File "jnius/jnius_conversion.pxi", line 252, in jnius.convert_jarray_to_python (jnius/jnius.c:10406)
ValueError: chr() arg not in range(256)
-------------------- >> begin captured logging << --------------------
biopax: INFO: Sending Pathway Commons query...
--------------------- >> end captured logging << ---------------------
```

**Comment by bgyori** [comment]
Fixed in 0f4e067e7ae3ca04ca8d43eafa1dba3232d88621
