### ISSUE TITLE
Fail to retrieve results from REACH

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#344]
```
INFO: indra/rasmachine - [1/591] Processing 29109595 for search terms: ['inflammation']
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.5 sec].
Adding annotator lemma
16:21:06.430 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Beginning to load the KBs for the rule-based bio NER...
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label BioProcess. This matcher contains 12 unique strings; the size of the first layer is 11.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label CellLine. This matcher contains 23 unique strings; the size of the first layer is 18.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label CellType. This matcher contains 8 unique strings; the size of the first layer is 6.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Cellular_component. This matcher contains 14 unique strings; the size of the first layer is 9.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Family. This matcher contains 128 unique strings; the size of the first layer is 95.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Gene_or_gene_product. This matcher contains 204 unique strings; the size of the first layer is 169.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Organ. This matcher contains 13 unique strings; the size of the first layer is 5.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Simple_chemical. This matcher contains 82 unique strings; the size of the first layer is 68.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Site. This matcher contains 47 unique strings; the size of the first layer is 46.
16:21:06.444 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label TissueType. This matcher contains 1 unique strings; the size of the first layer is 1.
16:21:12.450 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Gene_or_gene_product. This matcher contains 74582 unique strings; the size of the first layer is 62153.
16:21:21.348 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Family. This matcher contains 34805 unique strings; the size of the first layer is 27829.
16:21:21.362 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Cellular_component. This matcher contains 1388 unique strings; the size of the first layer is 873.
16:22:13.245 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Simple_chemical. This matcher contains 132037 unique strings; the size of the first layer is 78599.
16:22:13.540 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Site. This matcher contains 7312 unique strings; the size of the first layer is 3238.
16:22:13.541 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label BioProcess. This matcher contains 247 unique strings; the size of the first layer is 147.
16:22:13.549 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Species. This matcher contains 1944 unique strings; the size of the first layer is 1175.
16:22:14.119 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label CellLine. This matcher contains 72333 unique strings; the size of the first layer is 67250.
16:22:14.125 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label TissueType. This matcher contains 1312 unique strings; the size of the first layer is 1093.
16:22:14.149 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label CellType. This matcher contains 2631 unique strings; the size of the first layer is 1829.
16:22:14.544 [main] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Organ. This matcher contains 8704 unique strings; the size of the first layer is 5671.
16:22:14.544 [main] INFO  o.c.processors.bionlp.ner.KBLoader - KB loading completed.
macro=true
featureFactory=org.clulab.processors.bionlp.ner.BioNERFactory
Loading classifier from org/clulab/processors/bionlp/ner/bioner.dat ... done [1.0 sec].
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.2 sec].
Nov 08, 2017 4:22:15 PM edu.stanford.nlp.process.PTBLexer next
WARNING: Untokenizable:  (U+1C, decimal: 28)
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/choyt/dev/indra/indra/tools/machine/__main__.py", line 14, in <module>
    main()
  File "/home/choyt/.virtualenvs/indra_env/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/choyt/.virtualenvs/indra_env/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/choyt/.virtualenvs/indra_env/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/choyt/.virtualenvs/indra_env/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/choyt/.virtualenvs/indra_env/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/choyt/dev/indra/indra/tools/machine/cli.py", line 57, in run_with_search
    run_with_search_helper(model_path, config)
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 582, in run_with_search_helper
    twitter_cred=twitter_cred
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 437, in run_machine
    extend_model(model_path, model, pmids, start_time_local)
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 197, in extend_model
    rp, txt_format = process_paper(model_name, pmid)
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 114, in process_paper
    rp = reach.process_text(txt, citation=pmid, offline=True)
  File "/home/choyt/dev/indra/indra/sources/reach/reach_api.py", line 146, in process_text
    json_str = json_str.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by cthoyt** [comment]
This was an issue that was closed by updating some of the environment variables (in addition to ensuring the correctness of `JAVA_HOME` and `JDK_HOME`)

Check https://github.com/johnbachman/indra_deps_docker/blob/master/Dockerfile#L19-L26 and https://github.com/johnbachman/indra_deps_docker/blob/master/Dockerfile#L37

```sh
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export LC_ALL=en_US.UTF-8
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
```
