### ISSUE TITLE
Missing key 'hydrolysis'

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#346]
It seems that REACH results for hydrolysis are currently unhandled, and cause a crash

```
...
INFO: indra/rasmachine - [301/425] Processing 29136654 for search terms: ['inflammation']
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/choyt/dev/indra/indra/tools/machine/__main__.py", line 14, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/choyt/dev/indra/indra/tools/machine/cli.py", line 57, in run_with_search
    run_with_search_helper(model_path, config)
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 582, in run_with_search_helper
    twitter_cred=twitter_cred
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 437, in run_machine
    extend_model(model_path, model, pmids, start_time_local)
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 197, in extend_model
    rp, txt_format = process_paper(model_name, pmid)
  File "/home/choyt/dev/indra/indra/tools/machine/machine.py", line 114, in process_paper
    rp = reach.process_text(txt, citation=pmid, offline=True)
  File "/home/choyt/dev/indra/indra/sources/reach/reach_api.py", line 163, in process_text
    return process_json_str(json_str.decode('utf-8'), citation)
  File "/home/choyt/dev/indra/indra/sources/reach/reach_api.py", line 325, in process_json_str
    rp.get_modifications()
  File "/home/choyt/dev/indra/indra/sources/reach/processor.py", line 138, in get_modifications
    modification_type = modtype_to_inverse[modification_type]
KeyError: 'hydrolysis'
```

**Comment by bgyori** [comment]
Thanks, I was very surprised to see this first but it turns out, it's caused by some code I added very recently. I'll fix it right now.

**Comment by bgyori** [comment]
Done in f57d54dc0db53b00cee0fdef53de456f3c8b1050
