### ISSUE TITLE
Documentation errors on readthedocs.io

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#406]
We are getting the following errors on readthedocs.io (these can be reproduced locally too).

Import issue with indra.db:
```
/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/doc/modules/db/index.rst:10: WARNING: autodoc: failed to import module 'indra.db.manage_content'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'indra.db.manage_content'
```
Looks like PyBEL is not installed in this context, it should either be installed or mocked:
```
/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/doc/modules/sources/bel/index.rst:7: WARNING: autodoc: failed to import module 'indra.sources.bel.bel_api'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/sources/bel/__init__.py", line 1, in <module>
    from .bel_api import process_ndex_neighborhood
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/sources/bel/bel_api.py", line 9, in <module>
    from .pybel_processor import PybelProcessor
  File "/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/indra/sources/bel/pybel_processor.py", line 4, in <module>
    import pybel.constants as pc
ImportError: No module named 'pybel'
```

Signor nonexistent document warning:
```
/home/docs/checkouts/readthedocs.org/user_builds/indra/checkouts/latest/doc/modules/sources/index.rst:4: WARNING: toctree contains reference to nonexisting document 'modules/sources/signor/index'
```

**Comment by bgyori** [comment]
Fixed as of 45b07a7b4d14b54a1897bc29653188c4911c3073
