### ISSUE TITLE
Pin version of Kappy

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#438]
With the new release, kappy has an error on installation. In setup.py, the version is not currently pinned, so specifying it explicitly as the last version that worked would probably fix this.

```bash
[1029] [10:09] [choyt@lisa:~/dev/indra]
$ git rev-parse HEAD
e2027fa36bbe352bbc338ebc4381de2593cd6a63
```

```bash
[1027] [10:06] [choyt@lisa:~/dev/indra]
$ python3 -m pip install --user -e .
Obtaining file:///home/choyt/dev/indra
Requirement already satisfied: pysb>=1.3.0 in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: objectpath in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: rdflib==4.2.1 in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: requests>=2.11 in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: lxml in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: ipython in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: future in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: networkx==1.11 in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Requirement already satisfied: pandas in /home/choyt/.local/lib/python3.4/site-packages (from indra==1.6.0)
Collecting kappy (from indra==1.6.0)
  Downloading kappy-4.0.0.dev4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3mesr69h/kappy/setup.py", line 51, in <module>
        long_description=readme(),
      File "/tmp/pip-build-3mesr69h/kappy/setup.py", line 44, in readme
        with open('python/README.rst') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'python/README.rst'
```

**Comment by cthoyt** [comment]
Also I posted this on their GitHub (https://github.com/Kappa-Dev/KaSim/issues/518)

**Comment by cthoyt** [comment]
This seems to be a linux only problem due to the wheel builds. Not really a problem for INDRA to solve, but pinning it might be a good idea anyway

**Comment by bgyori** [comment]
Thanks! I thought about this and I think pinning to the latest version will fix this only to the extent that you would get an explicit error saying there is no version available for your current environment. That is still better than "silently" getting an old, broken version to be installed so I added this, and also made kappy an optional dependency.
