### ISSUE TITLE
Errors from cBio client

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#538]
The cBio web service has likely changed the format in which it returns results and our client needs to be adapted accordingly. Below is the relevant part of one of the errors:
```python
  File "/home/travis/build/sorgerlab/indra/indra/databases/context_client.py", line 66, in get_mutations
    mutations = cbio_client.get_ccle_mutations(gene_names, cell_types)
  File "/home/travis/build/sorgerlab/indra/indra/databases/cbio_client.py", line 335, in get_ccle_mutations
    case_id=cell_line)
  File "/home/travis/build/sorgerlab/indra/indra/databases/cbio_client.py", line 100, in get_mutations
    df = df[df['case_id'] == case_id]
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'case_id'
```

and another one

```python
Traceback (most recent call last):
  File "/home/travis/build/sorgerlab/bioagents/bioagents/__init__.py", line 86, in _respond_to
    reply_content = resp(content)
  File "/home/travis/build/sorgerlab/bioagents/bioagents/dtda/dtda_module.py", line 127, in respond_find_disease_targets
    self.dtda.get_top_mutation(disease.name)
  File "/home/travis/build/sorgerlab/bioagents/bioagents/dtda/dtda.py", line 194, in get_top_mutation
    'missense')
  File "/home/travis/build/sorgerlab/bioagents/bioagents/dtda/dtda.py", line 164, in get_mutation_statistics
    mutation_type)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/indra/databases/cbio_client.py", line 102, in get_mutations
    'mutation_type', mutation_type)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/indra/databases/cbio_client.py", line 452, in _filter_data_frame
    df.dropna(inplace=True, subset=relevant_cols)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pandas/core/frame.py", line 3489, in dropna
    raise KeyError(list(np.compress(check, subset)))
KeyError: ['gene_symbol', 'amino_acid_change', 'mutation_type']
```

**Comment by bgyori** [comment]
The cBio web service has since been fixed.
