### ISSUE TITLE
PyBEL test failures that appeared

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#552]
```
======================================================================
FAIL: indra.tests.test_pybel_assembler.test_rxn_no_controller
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_pybel_assembler.py", line 344, in test_rxn_no_controller
    pc.NAME: 'CHEBI:4170'
AssertionError
======================================================================
FAIL: indra.tests.test_pybel_assembler.test_rxn_with_controller
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_pybel_assembler.py", line 375, in test_rxn_with_controller
    pc.NAME: 'CHEBI:4170'
AssertionError
```

**Comment by cthoyt** [comment]
Was this because we added explicit removal of the `CHEBI:` prefix?
