### ISSUE TITLE
PubMed tests failing

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#571]
We probably just need to update these tests since the underlying searches return different results compared to before. @pagreene, could you look into this? Thanks!
```
======================================================================
FAIL: indra.tests.test_pubmed_client.test_get_no_ids
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_pubmed_client.py", line 18, in test_get_no_ids
    assert(not ids)
AssertionError
======================================================================
FAIL: indra.tests.test_pubmed_client.test_get_pmc_ids
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_pubmed_client.py", line 35, in test_get_pmc_ids
    i.startswith('4')]) == 10)
AssertionError: 
-------------------- >> begin captured logging << --------------------
pubmed: WARNING: Not all ids were retrieved for search braf[tw];
limited at 10.
--------------------- >> end captured logging << ---------------------
```

**Comment by pagreene** [comment]
Sure, I'll take a look.

**Comment by kkaris** [comment]
Looking into it
