### ISSUE TITLE
PyBEL neighborhood query test errors

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#575]
```
======================================================================
ERROR: indra.tests.test_bel.test_pybel_neighborhood_query
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/bgyori/indra/indra/tests/test_bel.py", line 34, in test_pybel_neighborhood_query
    bp = bel.process_pybel_neighborhood(['TP63'], corpus)
  File "/home/travis/build/bgyori/indra/indra/sources/bel/bel_api.py", line 106, in process_pybel_neighborhood
    bp = process_belscript(network_file)
  File "/home/travis/build/bgyori/indra/indra/sources/bel/bel_api.py", line 214, in process_belscript
    pybel_graph = pybel.from_path(file_name, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pybel/io/lines.py", line 74, in from_path
    **kwargs
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pybel/io/lines.py", line 43, in from_lines
    **kwargs
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pybel/io/line_utils.py", line 57, in parse_lines
    manager = Manager.ensure(manager)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pybel/manager/cache_manager.py", line 1565, in ensure
    return cls.from_connection(connection=connection, *args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pybel/manager/base_manager.py", line 105, in from_connection
    engine, session = _build_engine_session(connection=connection, *args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pybel/manager/base_manager.py", line 44, in _build_engine_session
    engine = create_engine(connection, echo=echo)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 52, in create
    plugins = u._instantiate_plugins(kwargs)
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'
```

**Comment by bgyori** [comment]
I haven't had time to look into this yet, @cthoyt , do you have any immediate tips what might have caused this?

**Comment by cthoyt** [comment]
Should be all set - the tests are passing for me locally on the latest commit from INDRA with today's new release of PyBEL (v0.11.6). Let me know how it works for you.
