### ISSUE TITLE
BEL example fails

### ISSUE THREAD

**Issue by scolby33** [sorgerlab/indra#769]
The example parsing of BEL from the documentation fails with a problem in PyBEL:

```
>>> from indra.sources import bel
>>> bel_processor = bel.process_pybel_neighborhood(['KRAS', 'BRAF'])
INFO: [2019-01-07 14:52:44] pybel.io.lines - Loading from path: /Users/scott/dev/indra/indra/sources/bel/../../../data/large_corpus.bel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scott/dev/indra/indra/sources/bel/api.py", line 106, in process_pybel_neighborhood
    bp = process_belscript(network_file)
  File "/Users/scott/dev/indra/indra/sources/bel/api.py", line 214, in process_belscript
    pybel_graph = pybel.from_path(file_name, **kwargs)
  File "/Users/scott/.virtualenvs/indra/lib/python3.7/site-packages/pybel/io/lines.py", line 48, in from_path
    parse_lines(graph=graph, lines=lines, **kwargs)
TypeError: parse_lines() got an unexpected keyword argument 'identifier_validation'
```

See related pybel/pybel#374

**Comment by cthoyt** [comment]
I'll check it out tomorrow

**Comment by bgyori** [comment]
Thanks, @scolby33! We actually have a standard test for this (https://github.com/sorgerlab/indra/blob/master/indra/tests/test_bel.py#L35) which is now failing so we can test progress on this with that test.
