### ISSUE TITLE
Model checker tests erroring on Travis

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#907]
Several model checker tests started erroring on Travis:
```
======================================================================
ERROR: indra.tests.test_model_checker.test_check_ubiquitination
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_model_checker.py", line 781, in test_check_ubiquitination
    checks = mc.check_model()
  File "/home/travis/build/sorgerlab/indra/indra/explanation/model_checker.py", line 351, in check_model
    result = self.check_statement(stmt, max_paths, max_path_length)
  File "/home/travis/build/sorgerlab/indra/indra/explanation/model_checker.py", line 374, in check_statement
    self.get_im()
  File "/home/travis/build/sorgerlab/indra/indra/explanation/model_checker.py", line 309, in get_im
    self._im = self.generate_im(self.model)
  File "/home/travis/build/sorgerlab/indra/indra/explanation/model_checker.py", line 209, in generate_im
    kappa = kappy.KappaStd()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/kappy/kappa_std.py", line 62, in __init__
    stderr=subprocess.STDOUT)
  File "/opt/python/3.5.6/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.5.6/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
-------------------- >> begin captured logging << --------------------
indra.assemblers.pysb.assembler: INFO: Using one_step assembly policy.
indra.assemblers.pysb.preassembler: DEBUG: Running PySB Preassembler replace activities
indra.assemblers.pysb.preassembler: DEBUG: 1/1 Ubiquitination(XIAP(), CASP3())
indra.explanation.model_checker: INFO: ---
indra.explanation.model_checker: INFO: Checking statement (1/1): Ubiquitination(XIAP(), CASP3())
indra.explanation.model_checker: INFO: Generating influence map
--------------------- >> end captured logging << ---------------------
```
It is not clear whether "Cannot allocate memory" is specific to the model checker or caused by some other change in INDRA that results in high memory usage.

**Comment by johnbachman** [comment]
Interesting. Is the kappy version pinned? If not, perhaps there has been a change in kappy's handling of IM generation that could have triggered it...

**Comment by bgyori** [comment]
Yes, the version of kappy is fixed to a stable one in setup.py

**Comment by dianakolusheva** [comment]
@bgyori When talking about adding tags in Travis, did you refer to running the model checker tests separately from the rest and restart the worker after the test is run similar to TEES tests? I am not sure how this can be tested though without pushing to master, as the tests are only failing in CRON tests.

```# First run TEES and Eidos tests separately for technical reasons
  - python -m nose_notify indra/tests/test_tees.py --slack_hook $SLACK_NOTIFY_HOOK
    --label "$TRAVIS_REPO_SLUG - $TRAVIS_BRANCH" -v -a $NOSEATTR --process-restartworker;
```
