### ISSUE TITLE
Memory allocation error on Travis related to BNG

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#952]
Recently, we have been getting memory allocation errors on Travis in a test that uses BNG via PySB. In particular, the equation generation step fails to start a new subprocess.

```
======================================================================
ERROR: indra.tests.test_eidos.test_eidos_to_pysb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_eidos.py", line 195, in test_eidos_to_pysb
    exp_str = pa.export_model(fmt)
  File "/home/travis/build/sorgerlab/indra/indra/assemblers/pysb/assembler.py", line 784, in export_model
    exp_str = pysb.export.export(self.model, format)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pysb/export/__init__.py", line 168, in export
    return e.export()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pysb/export/sbml.py", line 309, in export
    return libsbml.writeSBMLToString(self.convert(level=level))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pysb/export/sbml.py", line 124, in convert
    pysb.bng.generate_equations(self.model)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pysb/bng.py", line 731, in generate_equations
    verbose=verbose, **kwargs).split('\n'))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pysb/bng.py", line 671, in generate_network
    bngfile.execute()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pysb/bng.py", line 467, in execute
    stderr=subprocess.PIPE)
  File "/opt/python/3.5.6/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.5.6/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
-------------------- >> begin captured logging << --------------------
indra.assemblers.pysb.assembler: INFO: Using default assembly policy.
indra.assemblers.pysb.preassembler: DEBUG: Running PySB Preassembler replace activities
indra.assemblers.pysb.preassembler: DEBUG: 1/6 Influence(Event(conflict), Event(displacement))
indra.assemblers.pysb.preassembler: DEBUG: 2/6 Influence(Event(rise cost living conflict), Event(water))
indra.assemblers.pysb.preassembler: DEBUG: 3/6 Influence(Event(economic), Event(displacement))
indra.assemblers.pysb.preassembler: DEBUG: 4/6 Influence(Event(economic), Event(staple food water variety food))
indra.assemblers.pysb.preassembler: DEBUG: 5/6 Influence(Event(conflict), Event(violence))
indra.assemblers.pysb.preassembler: DEBUG: 6/6 Influence(Event(economic), Event(violence))
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
```

**Comment by bgyori** [comment]
This is similar to #907 in that it has to do with starting subprocesses so the solution to both is probably the same.

**Comment by bgyori** [comment]
This is still happening on and off on some of the builds.
